version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/sample-app
hooks:
  BeforeInstall:
    - location: scripts/install_node_and_pm2.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
