version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Zipping the build artifacts...
      - zip -r build.zip . -x "node_modules/*" "*.git*"

artifacts:
  files:
    - build.zip
  discard-paths: yes
